name: API Automation (Pytest + Newman)

on:
  push:
    branches: [development]
  pull_request:
    branches: [development]

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-html

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install Newman
        run: |
          npm install -g newman newman-reporter-htmlextra

      - name: Run Pytest API tests
        env:
          BASE_URL: https://jsonplaceholder.typicode.com
          AUTH_TOKEN: dummy-token
        run: |
          pytest -v -s \
          --html=reports/pytest-report.html \
          --self-contained-html

      - name: Run Newman collection
        run: |
          mkdir -p newman-report
          newman run postman/CRUD_VAL.postman_collection.json \
            -e postman/JSONplaceholder.postman_environment.json \
            --reporters cli,htmlextra \
            --reporter-htmlextra-export newman-report/newman.html

      - name: Upload Pytest report
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: reports/pytest-report.html

      - name: Upload Newman report
        uses: actions/upload-artifact@v4
        with:
          name: newman-report
          path: newman-report/newman.html
